version: '3'
services:
  # backend file
  backend:
    build: .
    ports:
      - "8080:8080"
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    volumes:
      - ./:/jamin/server
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8080 
  #database
  database:
  # dockerfile이 있는 위치
    build: ./database
  # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
    networks:
      - db_ip
networks:
  db_ip:
    ipv4_address: 172.20.0.15