version: '3'
services:
  #database
  database:
  # dockerfile이 있는 위치
    build: ./database
  # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "3306:3306"
    # volumes:
    #   - /..:/usr/src/server
  # backend file
  backend:
    build: ./app
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리
    ports:
      - "8080:8080"


